# Generated by Django 4.2.11 on 2024-04-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('city_name', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
        ),
    ]
